### ISSUE TITLE
Can't seem to get sonarr to refresh library with this...

### ISSUE THREAD

**Issue by JourneyOver** [cowmix88/Filebot-Scripts#2]
Mainly what the title says, no matter how many times I try I can't seem to get this to notify sonarr to refresh the libary once a tv show is downloaded completely..

This is currently the script I have setup in Qbittorrent to shoot off the script so it'll do its stuff.

`filebot -script C:\Users\timta\Dropbox\Public\Folders\Filebot\Groovy\amc.groovy --output "D:/Shows" --log-file amc.log --conflict auto -non-strict --filter "age < 50" --def subtitles=en deleteAfterExtract=y clean=y "ut_dir=%F" "ut_kind=multi" "ut_title=%N" "ut_label=%L" "sonarr=localhost:8989/C:\ProgramData\NzbDrone\bin|61829cf08e31439f92bc0301e5552e83"`

and this is in the amc logs afterwords.. Now I do notice it says parameter: sonarr = ****\* but for some reason it just doesn't seem to do anything at all, any way you can possible help me out? maybe I got my token wrong or something (It's the API in sonarr right?) or could it be something else?

```
Parameter:
subtitles = en
Parameter: deleteAfterExtract = y
Parameter: clean = y
Parameter: ut_dir = C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS
Parameter: ut_kind = multi
Parameter: ut_title = Bitten.S03E06.720p.HDTV.x264-KILLERS
Parameter: ut_label = 
Parameter: sonarr = *****
Roots: [C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS]
Read archive [bitten.s03e06.720p.hdtv.x264-killers.rar] and extract to [C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\.scratch\bitten.s03e06.720p.hdtv.x264-killers]
Extracting files [C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\.scratch\bitten.s03e06.720p.hdtv.x264-killers\Bitten.S03E06.720p.HDTV.x264-KILLERS.mkv]
Input: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\.scratch\bitten.s03e06.720p.hdtv.x264-killers\Bitten.S03E06.720p.HDTV.x264-KILLERS.mkv
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.nfo
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r00
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r01
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r02
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r03
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r04
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r05
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r06
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r07
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r08
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r09
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r10
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r11
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r12
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r13
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r14
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r15
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.sfv
Exclude: C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\Sample\sample-bitten.s03e06.720p.hdtv.x264-killers.mkv
Group: [order:airdate, tvs:bitten] => [Bitten.S03E06.720p.HDTV.x264-KILLERS.mkv]
Lookup: Checking for [English] embedded sub in [Bitten.S03E06.720p.HDTV.x264-KILLERS.mkv] => []
Lookup: No embedded sub found, searching for subtitles.
Get [English] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
Matched [Bitten.S03E06.720p.HDTV.x264-KILLERS.mkv] to [Bitten.S03E06.720p.HDTV.x264-KILLERS] via hash
Fetching [Bitten.S03E06.720p.HDTV.x264-KILLERS.srt]
Export [Bitten.S03E06.720p.HDTV.x264-KILLERS.srt] as: SubRip / UTF-8
Writing [Bitten.S03E06.720p.HDTV.x264-KILLERS.srt] to [Bitten.S03E06.720p.HDTV.x264-KILLERS.eng.srt]
Using TV Order: airdate
Rename episodes using [TheTVDB]
Auto-detected query: [Bitten]
Fetching episode data for [Bitten]
Apply Filter: {age < 50}
Include [Bitten - 3x05 - Of Sonders Weight]
Include [Bitten - 3x06 - Rule of Anger]
Include [Bitten - 3x07 - On the Brink]
Include [Bitten - 3x08 - Tili Tili Bom]
Include [Bitten - 3x09 - Shock the System]
Include [Bitten - 3x10 - Truth, Changes, Everything]
Auto-detected query: [Bitten]
Fetching episode data for [Bitten]
Apply Filter: {age < 50}
Include [Bitten - 3x05 - Of Sonders Weight]
Include [Bitten - 3x06 - Rule of Anger]
Include [Bitten - 3x07 - On the Brink]
Include [Bitten - 3x08 - Tili Tili Bom]
Include [Bitten - 3x09 - Shock the System]
Include [Bitten - 3x10 - Truth, Changes, Everything]
[MOVE] Rename [C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\.scratch\bitten.s03e06.720p.hdtv.x264-killers\Bitten.S03E06.720p.HDTV.x264-KILLERS.eng.srt] to [D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E06 - Rule of Anger.eng.srt]
[MOVE] Rename [C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\.scratch\bitten.s03e06.720p.hdtv.x264-killers\Bitten.S03E06.720p.HDTV.x264-KILLERS.mkv] to [D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E06 - Rule of Anger.mkv]
Processed 2 files
Bitten - S03E01 - Family, Of Sorts.eng.srt
Bitten - S03E01 - Family, Of Sorts.mkv
Bitten - S03E02 - Our Own Blood.eng.srt
Bitten - S03E02 - Our Own Blood.mkv
Bitten - S03E03 - Right Behind You.mkv
Bitten - S03E04 - A Quiet Dog.eng.srt
Bitten - S03E04 - A Quiet Dog.mkv
Bitten - S03E05 - Of Sonders Weight.mkv
Bitten - S03E06 - Rule of Anger.eng.srt
Bitten - S03E06 - Rule of Anger.mkv
Bitten - S03E10 - Truth, Changes, Everything.mkv
Found duplicates: [D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E01 - Family, Of Sorts.mkv, D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E02 - Our Own Blood.mkv, D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E03 - Right Behind You.mkv, D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E04 - A Quiet Dog.mkv, D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E05 - Of Sonders Weight.mkv, D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E06 - Rule of Anger.mkv, D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E10 - Truth, Changes, Everything.mkv]
Sort duplicates by quality: [Bitten - S03E01 - Family, Of Sorts.mkv] => [720.6]
Sort duplicates by quality: [Bitten - S03E02 - Our Own Blood.mkv] => [720.6]
Sort duplicates by quality: [Bitten - S03E03 - Right Behind You.mkv] => [720.6]
Sort duplicates by quality: [Bitten - S03E04 - A Quiet Dog.mkv] => [720.2]
Sort duplicates by quality: [Bitten - S03E05 - Of Sonders Weight.mkv] => [720.2]
Sort duplicates by quality: [Bitten - S03E06 - Rule of Anger.mkv] => [720.6]
Sort duplicates by quality: [Bitten - S03E10 - Truth, Changes, Everything.mkv] => [1080.2]
Best quality: [file:D:\Shows\TV Shows\Bitten\Season 03\Bitten - S03E10 - Truth, Changes, Everything.mkv, sort:1080.2]
Delete archive C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.rar
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r00
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r01
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r02
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r03
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r04
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r05
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r06
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r07
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r08
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r09
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r10
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r11
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r12
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r13
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r14
Delete archive volume C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.r15
Clean clutter files and empty folders
Delete C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.nfo
Delete C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\bitten.s03e06.720p.hdtv.x264-killers.sfv
Delete C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\Sample\sample-bitten.s03e06.720p.hdtv.x264-killers.mkv
Delete C:\Users\timta\Desktop\QBT\Bitten.S03E06.720p.HDTV.x264-KILLERS\Sample
Done ヾ(＠⌒ー⌒＠)ノ
```

**Comment by cowmix88** [comment]
You don't need the full path, just use the url and your key
"sonarr=localhost:8989|61829cf08e31439f92bc0301e5552e83"

the log hides the key for security which is why you see ***

**Comment by JourneyOver** [comment]
Well now I just keep getting 

> Parameter: ut_dir = C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]
> Parameter: ut_kind = multi
> Parameter: ut_title = Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]
> Parameter: ut_label = 
> Parameter: seriesFormat = D:/Shows/TV Shows/{n}/season {s.pad(2)}/{n} - {s00e00} - {t}
> Parameter: movieFormat = D:/Shows/Movies/{n} {[y, rating]}/{n}
> Parameter: animeFormat = D:/Shows/Anime/{n}/season {s.pad(2)}/{n} - {s00e00} - {t}
> Parameter: deleteAfterExtract = y
> Parameter: clean = y
> Parameter: sonarr = *****
> Roots: [C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]]
> Input: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv].mkv
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-001.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-002.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-003.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-004.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Torrent-Downloaded-from-ExtraTorrent.cc.txt
> Group: [order:airdate, tvs:game of thrones] => [Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv].mkv]
> Using TV Order: airdate
> Rename episodes using [TheTVDB]
> Auto-detected query: [Game of Thrones]
> Fetching episode data for [Game of Thrones]
> Fetching episode data for [Game of Stones]
> Apply Filter: {age < 150}
> Include [Game of Thrones - 6x01 - The Red Woman]
> Include [Game of Thrones - 6xSpecial 15 - The Story So Far]
> [MOVE] Rename [C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv].mkv] to [D:\Shows\TV Shows\Game of Thrones\season 06\Game of Thrones - S06E01 - The Red Woman.mkv]
> Processed 1 files
> Game of Thrones - S06E01 - The Red Woman.mkv
> Notify Sonarr: localhost:8989null
> Notifying Sonarr
> MalformedURLException: For input string: "8989null"
> Clean clutter files and empty folders
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-001.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-002.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-003.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-004.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Torrent-Downloaded-from-ExtraTorrent.cc.txt
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]
> Done ヾ(＠⌒ー⌒＠)ノ

this is how I have it in qbittorrent 

> filebot -script C:\Users\timta\Dropbox\Public\Folders\Filebot\Groovy\amc.groovy --log-file amc.log --conflict auto -non-strict --filter "age < 150" --def "ut_dir=%F" "ut_kind=multi" "ut_title=%N" "ut_label=%L" "seriesFormat=D:/Shows/TV Shows/{n}/season {s.pad(2)}/{n} - {s00e00} - {t}" "movieFormat=D:/Shows/Movies/{n} {[y, rating]}/{n}" "animeFormat=D:/Shows/Anime/{n}/season {s.pad(2)}/{n} - {s00e00} - {t}" deleteAfterExtract=y clean=y "sonarr=localhost:8989|6e7bff2e25e24317924907b16e6b7eee"

Dunno where it's pulling the null from exactly? unless it's because of 

> refreshSonarrLibrary(sonarr.host, sonarr.port, sonarr.path, sonarr.token)

The sonarr.path being in that in the script? if so shouldn't that go away maybe?

**Comment by JourneyOver** [comment]
Well that wasn't it either, because if I deleted that little snippit from the refreshsonarr library then I get 

> Parameter: ut_dir = C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]
> Parameter: ut_kind = multi
> Parameter: ut_title = Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]
> Parameter: ut_label = tv-sonarr
> Parameter: seriesFormat = D:/Shows/TV Shows/{n}/season {s.pad(2)}/{n} - {s00e00} - {t}
> Parameter: movieFormat = D:/Shows/Movies/{n} {[y, rating]}/{n}
> Parameter: animeFormat = D:/Shows/Anime/{n}/season {s.pad(2)}/{n} - {s00e00} - {t}
> Parameter: deleteAfterExtract = y
> Parameter: clean = y
> Parameter: sonarr = *****
> Roots: [C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]]
> Input: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv].mkv
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-001.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-002.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-003.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-004.jpg
> Exclude: C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Torrent-Downloaded-from-ExtraTorrent.cc.txt
> Group: [order:airdate, tvs:game of thrones] => [Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv].mkv]
> Using TV Order: airdate
> Rename episodes using [TheTVDB]
> Auto-detected query: [Game of Thrones]
> Fetching episode data for [Game of Thrones]
> Fetching episode data for [Game of Stones]
> Apply Filter: {age < 150}
> Include [Game of Thrones - 6x01 - The Red Woman]
> Include [Game of Thrones - 6xSpecial 15 - The Story So Far]
> [MOVE] Rename [C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv].mkv] to [D:\Shows\TV Shows\Game of Thrones\season 06\Game of Thrones - S06E01 - The Red Woman.mkv]
> Processed 1 files
> Game of Thrones - S06E01 - The Red Woman.mkv
> Notify Sonarr: localhost:8989
> Notifying Sonarr
> MalformedURLException: For input string: "89896e7bff2e25e24317924907b16e6b7eee"
> Clean clutter files and empty folders
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-001.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-002.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-003.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Screenshot-004.jpg
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]\Torrent-Downloaded-from-ExtraTorrent.cc.txt
> Delete C:\Users\timta\Desktop\QBT\Game.of.Thrones.S06E01.720p.HBO.WEBRip.AAC2.0.x264-monkee[ettv]
> Done ヾ(＠⌒ー⌒＠)ノ

Which pushed the port and the token together... Hope you can come along and help me out with this so I can finally get everything to work correctly and have filebot control everything :c

**Comment by JourneyOver** [comment]
Okay so it looks like I finally got it working to some extent, idk really tbh >..< anyways what it seemed like I had to do was add a / between the port and the | part so it ends up looking like 

>  "sonarr=localhost:8989/|6e7bff2e25e24317924907b16e6b7eee"

afterwords after a show has downloaded and going through the filebot stuff it ends up throwing 

> Notify Sonarr: localhost:8989/
> Notifying Sonarr
> http://localhost:8989//api/Series
> Sonarr: Found matching series [Damien] => [14]
> Sonarr: Force file rescan of [14]
> http://localhost:8989//api/Command
> Sonarr: [body:[completionMessage:Completed, name:RescanSeries, sendUpdatesToClient:true, seriesId:14, trigger:manual, updateScheduledTask:true], id:4128, manual:true, name:RescanSeries, priority:normal, queued:0001-01-01T00:00:00Z, sendUpdatesToClient:true, startedOn:0001-01-01T00:00:00Z, state:queued, status:queued, trigger:manual, updateScheduledTask:true]

at the end of the log. Now I dunno how it worked since it doesn't seem to put the api in where it says api in the url ( I didn't delete the api that's literally how it came out in the end in the log) and it adds a double // as well after the port along with spamming up the last bit with the sonarr stuff repeating parts, but anyways it seemed to work anyways so I guess in the end it's good now :D 

So glad to have this working as I like sonarr but filebot was really the only thing stopping me from using it to begin with until now.

**Comment by cowmix88** [comment]
Glad you were able to get it working! :) Sorry that it takes me a while to check on here.
